# Online/Offline
mapping_online: false
real_time: false

# Topics
points_topic: "/kitti/velo/pointcloud"
imus_topic: "/kitti/oxts/imu"

# Extrinsics
estimate_extrinsics: false
print_extrinsics: false
initial_gravity: [0.0, 0.0, +9.807]
I_Translation_L: [-8.086759e-01, 3.195559e-01, -7.997231e-01]
I_Rotation_L: [
  9.999976e-01, 7.553071e-04, -2.035826e-03,
  -7.854027e-04, 9.998898e-01, -1.482298e-02,
  2.024406e-03, 1.482454e-02, 9.998881e-01
]

# Delays
LiDAR_noise: 0.001
empty_lidar_time: 1.0       # Should be at least [FULL_ROTATION_TIME]
real_time_delay: 0.5        # Should be at least [FULL_ROTATION_TIME] (without a modificated LiDAR driver)

# LiDAR
full_rotation_time: 0.10
min_dist: 4
ds_rate: 16

# IMU
imu_rate: 1000
covariance_gyroscope: 6.01e-4
covariance_acceleration: 1.53e-2
covariance_bias_gyroscope: 1.54e-5
covariance_bias_acceleration: 3.38e-4

# Localizator
MAX_NUM_ITERS: 3
# LIMITS: [0.001] * 23
NUM_MATCH_POINTS: 5
MAX_DIST_PLANE: 2.0
PLANES_THRESHOLD: 1.e-1

# Delta refinement
Heuristic:
  times: [1.0, 2.0]
  deltas: [0.1, 0.025, 0.005]